#!C:\Users\rithi\Desktop\DS_PRO\Own Pro\ML projects\Gemstone_price_analysis\v_env\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
